apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickers-mogo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickers-mogo
  template:
    metadata:
      labels:
        app: tickers-mogo
    spec:
      containers:
        - name: tickers-mogo
          image: mongo
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'

---
apiVersion: v1
kind: Service
metadata:
  name: tickers-mongo-srv
spec:
  selector:
    app: tickers-mogo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
